-- MySQL Script generated by MySQL Workbench
-- 15 يول, 2015 WET 08:20:19 م
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estore` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `estore` ;

-- -----------------------------------------------------
-- Table `estore`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`users` (
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `activated` TINYINT(1) NOT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estore`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`stores` (
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `users_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_stores_users_idx` (`users_uuid` ASC),
  CONSTRAINT `fk_stores_users`
    FOREIGN KEY (`users_uuid`)
    REFERENCES `estore`.`users` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estore`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`products` (
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `currency` VARCHAR(45) NULL,
  `image` LONGBLOB NULL,
  `type` VARCHAR(45) NULL,
  `size` INT NULL,
  `number` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `stores_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_products_stores1_idx` (`stores_uuid` ASC),
  CONSTRAINT `fk_products_stores1`
    FOREIGN KEY (`stores_uuid`)
    REFERENCES `estore`.`stores` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
